// https://tc39.es/ecma262/multipage/text-processing.html#sec-runtime-semantics-unicodematchproperty-p

/** Binary Unicode Property */
export enum BU {
  ASCII = '\\p{ASCII}',
  ASCIIHexDigit = '\\p{ASCII_Hex_Digit}',
  Alphabetic = '\\p{Alphabetic}',
  Any = '\\p{Any}',
  Assigned = '\\p{Assigned}',
  BidiControl = '\\p{Bidi_Control}',
  BidiMirrored = '\\p{Bidi_Mirrored}',
  CaseIgnorable = '\\p{Case_Ignorable}',
  Cased = '\\p{Cased}',
  ChangesWhenCasefolded = '\\p{Changes_When_Casefolded}',
  ChangesWhenCasemapped = '\\p{Changes_When_Casemapped}',
  ChangesWhenLowercased = '\\p{Changes_When_Lowercased}',
  ChangesWhenNFKCCasefolded = '\\p{Changes_When_NFKC_Casefolded}',
  ChangesWhenTitlecased = '\\p{Changes_When_Titlecased}',
  ChangesWhenUppercased = '\\p{Changes_When_Uppercased}',
  Dash = '\\p{Dash}',
  DefaultIgnorableCodePoint = '\\p{Default_Ignorable_Code_Point}',
  Deprecated = '\\p{Deprecated}',
  Diacritic = '\\p{Diacritic}',
  Emoji = '\\p{Emoji}',
  EmojiComponent = '\\p{Emoji_Component}',
  EmojiModifier = '\\p{Emoji_Modifier}',
  EmojiModifierBase = '\\p{Emoji_Modifier_Base}',
  EmojiPresentation = '\\p{Emoji_Presentation}',
  ExtendedPictographic = '\\p{Extended_Pictographic}',
  Extender = '\\p{Extender}',
  GraphemeBase = '\\p{Grapheme_Base}',
  GraphemeExtend = '\\p{Grapheme_Extend}',
  HexDigit = '\\p{Hex_Digit}',
  IDSBinaryOperator = '\\p{IDS_Binary_Operator}',
  IDSTrinaryOperator = '\\p{IDS_Trinary_Operator}',
  IDContinue = '\\p{ID_Continue}',
  IDStart = '\\p{ID_Start}',
  Ideographic = '\\p{Ideographic}',
  JoinControl = '\\p{Join_Control}',
  LogicalOrderException = '\\p{Logical_Order_Exception}',
  Lowercase = '\\p{Lowercase}',
  Math = '\\p{Math}',
  NoncharacterCodePoint = '\\p{Noncharacter_Code_Point}',
  PatternSyntax = '\\p{Pattern_Syntax}',
  PatternWhiteSpace = '\\p{Pattern_White_Space}',
  QuotationMark = '\\p{Quotation_Mark}',
  Radical = '\\p{Radical}',
  RegionalIndicator = '\\p{Regional_Indicator}',
  SentenceTerminal = '\\p{Sentence_Terminal}',
  SoftDotted = '\\p{Soft_Dotted}',
  TerminalPunctuation = '\\p{Terminal_Punctuation}',
  UnifiedIdeograph = '\\p{Unified_Ideograph}',
  Uppercase = '\\p{Uppercase}',
  VariationSelector = '\\p{Variation_Selector}',
  WhiteSpace = '\\p{White_Space}',
  XIDContinue = '\\p{XID_Continue}',
  XIDStart = '\\p{XID_Start}',

  BasicEmoji = '\\p{Basic_Emoji}',
  EmojiKeycapSequence = '\\p{Emoji_Keycap_Sequence}',
  RGIEmojiModifierSequence = '\\p{RGI_Emoji_Modifier_Sequence}',
  RGIEmojiFlagSequence = '\\p{RGI_Emoji_Flag_Sequence}',
  RGIEmojiTagSequence = '\\p{RGI_Emoji_Tag_Sequence}',
  RGIEmojiZWJSequence = '\\p{RGI_Emoji_ZWJ_Sequence}',
  RGIEmoji = '\\p{RGI_Emoji}',
}
