// https://unicode.org/reports/tr18/#General_Category_Property

/** General Category */
export enum GC {
  Letter = '\\p{L}',
  UppercaseLetter = '\\p{Lu}',
  LowercaseLetter = '\\p{Ll}',
  TitlecaseLetter = '\\p{Lt}',
  ModifierLetter = '\\p{Lm}',
  OtherLetter = '\\p{Lo}',
  Mark = '\\p{M}',
  NonSpacingMark = '\\p{Mn}',
  SpacingCombiningMark = '\\p{Mc}',
  EnclosingMark = '\\p{Me}',
  Number = '\\p{N}',
  DecimalDigitNumber = '\\p{Nd}',
  LetterNumber = '\\p{Nl}',
  OtherNumber = '\\p{No}',
  Symbol = '\\p{S}',
  MathSymbol = '\\p{Sm}',
  CurrencySymbol = '\\p{Sc}',
  ModifierSymbol = '\\p{Sk}',
  OtherSymbol = '\\p{So}',
  Punctuation = '\\p{P}',
  ConnectorPunctuation = '\\p{Pc}',
  DashPunctuation = '\\p{Pd}',
  OpenPunctuation = '\\p{Ps}',
  ClosePunctuation = '\\p{Pe}',
  InitialPunctuation = '\\p{Pi}',
  FinalPunctuation = '\\p{Pf}',
  OtherPunctuation = '\\p{Po}',
  Separator = '\\p{Z}',
  SpaceSeparator = '\\p{Zs}',
  LineSeparator = '\\p{Zl}',
  ParagraphSeparator = '\\p{Zp}',
  Other = '\\p{C}',
  Control = '\\p{Cc}',
  Format = '\\p{Cf}',
  Surrogate = '\\p{Cs}',
  PrivateUse = '\\p{Co}',
  Unassigned = '\\p{Cn}',
}
